"use client";

import React, { useState } from "react";

export default function Home() {
  const [count, setCount] = useState<number>(0);

  return (
    <div style={styles.container}>
      {/* Glow Effects */}
      <div style={styles.glowTop} />
      <div style={styles.glowBottom} />

      {/* Main Content */}
      <div style={styles.content}>
        <div style={styles.badgeContainer}>
          <div style={styles.badgeIcon}>⚡</div>
          <span style={styles.badgeText}>NEXT.JS STARTER KIT (TS)</span>
        </div>

        <h1 style={styles.title}>Welcome to Next.js App</h1>
        
        <p style={styles.description}>
          A minimal, production-ready Next.js layout generated by <strong>@imksh/cli</strong>. Everything is set up and ready to customize.
        </p>

        {/* Feature List */}
        <div style={styles.grid}>
          <div style={styles.card}>
            <h3 style={styles.cardTitle}>📂 App Router</h3>
            <p style={styles.cardText}>Built using the Next.js App Router with layouts and nested routes.</p>
          </div>
          <div style={styles.card}>
            <h3 style={styles.cardTitle}>⚡ Fast Refresh</h3>
            <p style={styles.cardText}>Instant feedback on edits. Optimized bundling and server-side rendering.</p>
          </div>
          <div style={styles.card}>
            <h3 style={styles.cardTitle}>🛠️ Structure</h3>
            <p style={styles.cardText}>Pre-configured workspace folders for pages, hooks, services, and configs.</p>
          </div>
          <div style={styles.card}>
            <h3 style={styles.cardTitle}>⚙️ Zero Config</h3>
            <p style={styles.cardText}>Pure ES6 components loaded and ready to boot without configuration.</p>
          </div>
        </div>

        {/* Action Row */}
        <div style={styles.actionRow}>
          <button 
            style={styles.primaryButton}
            onClick={() => setCount((prev) => prev + 1)}
          >
            Count: {count}
          </button>
          <button 
            style={styles.secondaryButton}
            onClick={() => alert("Welcome to @imksh/cli Next.js TypeScript template!")}
          >
            Get Started
          </button>
        </div>

        {/* Footer */}
        <div style={styles.footer}>
          Generated with @imksh/cli • Version 1.0.0
        </div>
      </div>
    </div>
  );
}

const styles: { [key: string]: React.CSSProperties } = {
  container: {
    height: "100vh",
    width: "100vw",
    overflow: "hidden",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#030712",
    backgroundImage: "radial-gradient(circle at center, #0f172a 0%, #030712 100%)",
    color: "#f8fafc",
    fontFamily: "system-ui, -apple-system, sans-serif",
    padding: "24px",
    boxSizing: "border-box",
  },
  glowTop: {
    position: "absolute",
    top: "15%",
    left: "20%",
    width: "350px",
    height: "350px",
    backgroundColor: "rgba(59, 130, 246, 0.12)",
    borderRadius: "50%",
    filter: "blur(80px)",
    zIndex: 1,
    pointerEvents: "none",
  },
  glowBottom: {
    position: "absolute",
    bottom: "15%",
    right: "20%",
    width: "350px",
    height: "350px",
    backgroundColor: "rgba(99, 102, 241, 0.08)",
    borderRadius: "50%",
    filter: "blur(80px)",
    zIndex: 1,
    pointerEvents: "none",
  },
  content: {
    maxWidth: "800px",
    width: "100%",
    textAlign: "center",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  badgeContainer: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    border: "1px solid rgba(59, 130, 246, 0.25)",
    padding: "8px 16px",
    borderRadius: "16px",
    marginBottom: "16px",
  },
  badgeIcon: {
    fontSize: "18px",
  },
  badgeText: {
    fontSize: "11px",
    fontWeight: "bold",
    letterSpacing: "0.15em",
    color: "#60a5fa",
  },
  title: {
    fontSize: "42px",
    fontWeight: "900",
    letterSpacing: "-0.02em",
    margin: "0 0 16px 0",
    backgroundImage: "linear-gradient(to right, #ffffff, #cbd5e1)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  description: {
    fontSize: "15px",
    color: "#94a3b8",
    maxWidth: "540px",
    lineHeight: "1.6",
    margin: "0 0 40px 0",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "16px",
    width: "100%",
    maxWidth: "680px",
    marginBottom: "40px",
  },
  card: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    border: "1px solid rgba(255, 255, 255, 0.06)",
    padding: "20px",
    borderRadius: "16px",
    textAlign: "left",
    transition: "background 0.2s ease",
  },
  cardTitle: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#ffffff",
    margin: "0 0 6px 0",
  },
  cardText: {
    fontSize: "12px",
    color: "#64748b",
    lineHeight: "1.5",
    margin: 0,
  },
  actionRow: {
    display: "flex",
    gap: "16px",
    marginBottom: "32px",
  },
  primaryButton: {
    backgroundColor: "#2563eb",
    border: "none",
    color: "#ffffff",
    padding: "12px 28px",
    borderRadius: "12px",
    fontSize: "14px",
    fontWeight: "bold",
    cursor: "pointer",
    boxShadow: "0 10px 15px -3px rgba(37, 99, 235, 0.2)",
    transition: "transform 0.1s ease",
  },
  secondaryButton: {
    backgroundColor: "transparent",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    color: "#f8fafc",
    padding: "12px 28px",
    borderRadius: "12px",
    fontSize: "14px",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  footer: {
    fontSize: "11px",
    color: "#475569",
    fontWeight: "500",
  },
};
