import type { EditorThemeClasses } from 'lexical';

/**
 * Lexical editor theme — maps node types to CSS class names.
 * All classes use the `rte-` prefix to avoid conflicts.
 */
export const editorTheme: EditorThemeClasses = {
  root: 'rte-root',
  paragraph: 'rte-paragraph',
  heading: {
    h1: 'rte-h1',
    h2: 'rte-h2',
    h3: 'rte-h3',
    h4: 'rte-h4',
    h5: 'rte-h5',
  },
  text: {
    bold: 'rte-bold',
    italic: 'rte-italic',
    underline: 'rte-underline',
    strikethrough: 'rte-strikethrough',
    code: 'rte-inline-code',
    subscript: 'rte-subscript',
    superscript: 'rte-superscript',
  },
  quote: 'rte-blockquote',
  list: {
    ul: 'rte-list-ul',
    ol: 'rte-list-ol',
    listitem: 'rte-listitem',
    listitemChecked: 'rte-listitem-checked',
    listitemUnchecked: 'rte-listitem-unchecked',
    nested: {
      listitem: 'rte-nested-listitem',
    },
  },
  link: 'rte-link',
  code: 'rte-code-block',
  codeHighlight: {
    atrule: 'rte-token-atrule',
    attr: 'rte-token-attr',
    boolean: 'rte-token-boolean',
    builtin: 'rte-token-builtin',
    cdata: 'rte-token-cdata',
    char: 'rte-token-char',
    class: 'rte-token-class',
    'class-name': 'rte-token-class-name',
    comment: 'rte-token-comment',
    constant: 'rte-token-constant',
    deleted: 'rte-token-deleted',
    doctype: 'rte-token-doctype',
    entity: 'rte-token-entity',
    function: 'rte-token-function',
    important: 'rte-token-important',
    inserted: 'rte-token-inserted',
    keyword: 'rte-token-keyword',
    namespace: 'rte-token-namespace',
    number: 'rte-token-number',
    operator: 'rte-token-operator',
    prolog: 'rte-token-prolog',
    property: 'rte-token-property',
    punctuation: 'rte-token-punctuation',
    regex: 'rte-token-regex',
    selector: 'rte-token-selector',
    string: 'rte-token-string',
    symbol: 'rte-token-symbol',
    tag: 'rte-token-tag',
    url: 'rte-token-url',
    variable: 'rte-token-variable',
  },
  table: 'rte-table',
  tableCell: 'rte-table-cell',
  tableCellHeader: 'rte-table-cell-header',
  tableRow: 'rte-table-row',
  image: 'rte-image',
  horizontalRule: 'rte-hr',
};
